### ISSUE TITLE
Modules need to handle incorrect input without crashing

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#103]
When a workflow is restored and something is changed, the input for the subsequent modules can be incorrect. Instead of crashing, the program should throw a popup error, refresh the options for the module with the updated data, and allow the user to choose and continue running the workflow.

**Comment by tisaconundrum2** [comment]
Sounds good. I'll make sure to implement that.

**Comment by ryanbanderson** [comment]
Also make sure that all input is provided. Currently when regression train is missing an x variable, it runs, throws an exception, and just grays out the module. It's good that it doesn't kill the whole PySAT, but would be better to pop up a warning and give the user a chance to select a variable without having to add a new module.

**Comment by tisaconundrum2** [comment]
Future does this correctly.

Use Debug Mode to change direction of stdout. 
<br>This will allow you to crash the program intentionally and get a location of where the error originated
