### ISSUE TITLE
no attribute coef_

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#106]
- GP
- ElasticNetCV
- LassoLarsCV
- KernelRidge (KRR)

**Comment by ryanbanderson** [comment]
LassoLarsCV and ElasticNetCV both have coef_ attributes according to the scikit documentation. They should work just like the other regression models.

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoLarsCV.html
http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNetCV.html

**Comment by tisaconundrum2** [comment]
- ElasticNetCV
- LassoLarsCV

have been fixed in 5e79b56

**Comment by tisaconundrum2** [comment]
Closing for now, GP and KRR will be looked at again later.
