### ISSUE TITLE
Returning error ('meta', 'Folds') in CV

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#107]
pysat/regression/cv.py:37: cv_iterator = LeaveOneLabelOut([('meta', 'Folds')]) Fails giving error ('meta', 'Folds')

![image](https://user-images.githubusercontent.com/11879769/30946732-9b099f06-a3ba-11e7-8f31-8c19cbbe5857.png)

**Comment by ryanbanderson** [comment]
You can't run CV until you define folds over which to cross validate...

**Comment by tisaconundrum2** [comment]
Of course.
