### ISSUE TITLE
Make all regression methods able to use cross validation

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#120]
Currently only PLS can be cross validated using the CV module. GP is included but the interface doesn't have text fields to enter comma separated parameter values. All other regression methods should be added as well. For methods that have their own built-in CV, the fields should be populated with the default settings from their CV.

**Comment by tisaconundrum2** [comment]
Should I just turn all the spinboxes into lineEdits?

**Comment by ryanbanderson** [comment]
Yep, unless you can come up with a better way for the user to specify multiple values for each input.

**Comment by tisaconundrum2** [comment]
Closing, as this seems to have been finished
