### ISSUE TITLE
How to solve the  Qlayout Problem? 

### ISSUE THREAD

**Issue by shuchong2018** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#125]
When I select loadData and other menu items, the GUI can't open it and it promot Qlayout: Attempting to add Qlayout "" to Qwidget "loadDATA", wich already has a layout.
Look forward to your reply! 
Thank you very much.

**Comment by tisaconundrum2** [comment]
Hello, thank you for adding this issue. We'll resolve and push a new version out quickly

**Comment by tisaconundrum2** [comment]
QLayout problem should be resolved now. Follow the instructions [here](https://github.com/USGS-Astrogeology/PySAT_Point_Spectra_GUI/blob/master/README.md) [https://github.com/USGS-Astrogeology/PySAT_Point_Spectra_GUI/blob/master/README.md](https://github.com/USGS-Astrogeology/PySAT_Point_Spectra_GUI/blob/master/README.md)
