### ISSUE TITLE
Radio button hint 

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#13]
![image](https://cloud.githubusercontent.com/assets/11879769/25597418/66ed9ed6-2e83-11e7-88d3-ad69e6f0d425.png)
Make the radio button output a hint: "Set a breakpoint here"

**Comment by ryanbanderson** [comment]
Closing this. I don't think we're doing breakpoints for now.
