### ISSUE TITLE
Prevent widgets and windows from getting ridiculously wide or tiny

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#132]
Especially when running cross validation with a large number of parameters (e.g. the new default LAsso or elastic net settings), the drop down in subsequent modules to show the CV results or the names of the models trained is absurdly wide. We need to fix this.

On the other hand, when cross validation is added to the workflow, it shrinks everything, and the user has to adjust the main window size to get everything to snap back into place. This also needs to be fixed.

**Comment by tisaconundrum2** [comment]
@me Check the `Form.resize`'s inside the UI

**Comment by tisaconundrum2** [comment]
@me For issues with the name changing the size of the widget, consider cutting out redundancies in the name

**Comment by tisaconundrum2** [comment]
A few more tests to make sure this is still working, and then i'll close.

**Comment by tisaconundrum2** [comment]
As a developer I will want to 
 - Set a maximum char limit for comboBoxes
 - Only record the items that are changed
This should reduce some of the length issues that we are seeing
