### ISSUE TITLE
Make later modules able to handle changes to earlier modules

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#134]
For example: I change the element I'm predicting from SiO2 to Al2O3. If later on in the workflow I run predictions with "SiO2" in the model name, the workflow will break if I try to run it with Al2O3 because the SiO2 models don't exist. So I have to delete everything and re-create it, which defeats the purpose of restoring the workflow. This is a big enough nuisance that I'm marking it high priority.

Easier fix: Elegantly fail if a combobox or list widget refers to something that no longer exists, and refresh the module inputs to get the current options.

Harder fix: dynamically update the options on all later modules when an earlier setting is changed.

**Comment by tisaconundrum2** [comment]
<mxfile userAgent="Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0" version="7.7.1" editor="www.draw.io" type="device"><diagram id="f26a45f4-9382-392f-729c-cb17672f4a49" name="Page-1">5Vffb9sgEP5rom0PqxyTpO1jl/7YpE2r1EldH4l9NrQELIybZH/9OAwhjpOoVbeq2vrQwAcc9313HHhApvPllaYV+6ZyEIM0yZcDcj5I02E6HNkfRFYtcjwhLVBqnvtJEbjhv8CDiUcbnkPdmWiUEoZXXTBTUkJmOhjVWi260wolurtWtIQecJNR0UdveW5Yi56Mk4h/Bl6ysPMw8SMzmj2UWjXS7zdISeH+2uE5Dbb8/JrRXC02IHIxIFOtlGlb8+UUBGobZGvXXe4ZXfutQZqnLJi0Cx6paDz1jEH2gDMK1JdRWdpApMkCNDgCOXjPzSqoBbkVz3eVNkyVSlJxEdFPThHAPRPbY2YubHNom7Dk5ifCR2Pfuwsj0ujVxhB277yBezBm5bOGNkZZKO77VanK22g9Rff2yuOhWjU687NSn3BUl+BnkXVobMqDmoN1xk7RIKjhj13r1OdeuZ4X9bcNH4Ld4Uh74bBnqxGo/LAnexQVuS4YN3BTUcdiYY9lV2hvGLSB5WEx+jTDgpDk/lCfjtvuIp6QYchrtnE6JsnLhTl+Xp5O6Bz5y1ldOe7/Rd6Sft6OXilvyf68Td9c3qbpKybuyb+edS9NMb/0WnG7SYzZpBuzUYhZMNFmuV+1FY61G0+K0Gh/7pI3l7tk9Iq5e9pTxlZWYZCk9XpSYuv77N4+wFygz8KotRsnBLAKwJnbo2hM074onNhYuiVYYfGhh+8oHGqqnBqHzWjtfpVE6gwMA43dBv9njXZyBluoBK3Xt0K+4Va17VX081pQNK7wOqHG2HfcBqOZ3l54mOMtuMdpI9DpHAlRZAY1eklLyqVrWRruqNRGacePy0Jp+0jkSHR76y/oGjfvkFrOiwJa1lN366GdRsYnsX222vNRB82oEz1oTS771nl91fBpq9j7D4c0282S0UfwPAtBS/THCerCWQOEq7rGPGRcljFARwdl3r//X162dfTtITbd810brR5gqoTSFpFKYvEuuBBbUG0rBBIm5+PY++Hq7sc02VNHlK0bhXDfBoznOcjexfAHystoq7wMwwfYRnkhZEd5sSufXV9sN37YtIU6fj2Si98=</diagram></mxfile>

**Comment by tisaconundrum2** [comment]
Some of the edge cases that need to be looked at
 - When names are being changed in Regression/CV make sure the propagate correctly through the rest of the UI
 - Test to make sure that saving before a selective restore does not break the UI

**Comment by tisaconundrum2** [comment]
The problem that was occurring for widgets Regression/CV was having to do with the fact that the functionality wasn't applied yet to these widgets.

**Comment by tisaconundrum2** [comment]
@AustinSanders is this issues ready to be closed?
