### ISSUE TITLE
Scroll down when a new widget is added so that it is visible

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#140]
I tried to implement this by adding the following code to addWidget under MainWindow.py:
`scrollbar = self.scrollArea.verticalScrollBar()`
`scrollbar.setValue(scrollbar.maximum())`

When I step through line by line to debug, it works. But when I run the code it doesn't scroll.

**Comment by ianeece** [comment]
looks like the default maximum value of 99 wasn't large enough.  I added this line before the setValue line, and it seems to be working:

scrollbar.setMaximum(500)

**Comment by ianeece** [comment]
maxed out after 7 modules, so changed to:

scrollbar.setMaximum(500000)
