### ISSUE TITLE
Normalization has an issue with saving and restoring wavelengths

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#142]
https://github.com/tisaconundrum2/PySAT_Point_Spectra_GUI/commit/67b3059272420345f697451058820f3964a71538

As a user I want to be able to save and restore the ranges in Normalization
As a developer, it might be best to override Qtickle's getGui and force it to save the wavelengths, and upon restore automatically restore wavelengths by calling the add range button.

**Comment by ryanbanderson** [comment]
I think I have a solution for this. I'm going to work on some of the other issues with normalization before pushing it to master.

**Comment by tisaconundrum2** [comment]
Normalization does in fact save the necessary wavelengths, however in order to see them, you still have to press the add ranges button.

**Comment by ryanbanderson** [comment]
Found a better solution for this, see #150
