### ISSUE TITLE
Unknown bug that causes modules to stop loading into MainWindow

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#143]
A bug that prevents the user from interacting with modules. It's almost as if `connect()` stop altogether. 

A possible way to reproduce the bug?

>I accidentally put in a range of 1-100 for the normalization instead of 1000 and so when I went to the cross validation step, wavelength wasn't an option to select (since we have no wavelengths below 100). So I tried to go back and but couldn't for some reason and so I closed that workflow and opened a new one thinking to start from the beginning but I was unable to load data. The window was basically just a blank screen with a white box - no boxes to select a file. So I hit OK and it said *.csv is not a valid name (duh, that box wasn't even showing anymore) and that my module is broke and I should fix it. I tried reloading a previously save module and it failed to load giving the same message. I shut it down and opened a new cmd window and started from "activate" and it still opens in the same way - no boxes to load data. I guess I have to start from step 3 again to reinstall?

Things that have been tried.

- uninstalling the environment, uninstalling anaconda, reinstalling anaconda, reinstalling pysat
- moved the window size around a bit and nothing seemed to change
- tried using `conda env remove -n point_spectra_gui`
- can open previously saved file but fails to load.  Displays `Error: list indices must be integers or slices, not str`
![image](https://user-images.githubusercontent.com/11879769/32626900-ea9fc162-c54d-11e7-94fb-86d9d902dd3b.png)
![image](https://user-images.githubusercontent.com/11879769/32626905-ecdc38f2-c54d-11e7-9b02-ee7765ec85d4.png)

**Comment by tisaconundrum2** [comment]
I have no idea how to replicate this bug. I just tried installing our software on a completely different machine, that has never seen our software. I don't know why it's breaking.

**Comment by TheCyaniteProject** [comment]
The specific issue I had:
     I came across a UI bug where when I clicked “Load Data” from the File drop down, nothing would happen. It turns out that the frame that was holding the data entry was being blocked, and as a result was not displaying.

Cause:
  The specific cause of this is unknown but the likely cause is my switching between themes multiple times (or perhaps even once).

Quick Fix:
  A quick fix for this problem would be to simply drag down the vertical splittler. This will create a miss-aligned UI, but that contains all of the missing UI. To fix the miss-alignment, you can resize the window as well, which will fix the issue permanently (assuming you have already opened “Load Data”, and have moved the Splitter down) for the current window.

![image](https://user-images.githubusercontent.com/26806429/32701210-e1fce760-c796-11e7-9674-097af0b42525.png)

![image](https://user-images.githubusercontent.com/26806429/32701187-a1678732-c796-11e7-8eec-2671861527e4.png)
