### ISSUE TITLE
Normalization bug with Add Range

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#145]
![a76a1a3b-ac0b-4b20-980f-61b8f2a4140c](https://user-images.githubusercontent.com/11879769/32852733-168d153e-c9f6-11e7-9c7e-f83d65555877.gif)

As a user when I restore Normalization I have to press Add Range button repeatedly before new ranges are added.
As a developer, this could probably be fixed by adding a check in the `hide_settings()` function

![a628f8a2-09ad-42cf-a7ee-14d6d7ca96da](https://user-images.githubusercontent.com/11879769/32863019-4bcc8a7e-ca17-11e7-8c13-87a0b8109f3d.gif)

As a user when I press Delete Range, an error Cannot delete shows up

**Comment by ryanbanderson** [comment]
I think this issue is resolved.
