### ISSUE TITLE
Specify directory and file name

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#15]
![image](https://cloud.githubusercontent.com/assets/11879769/25768347/79125ea8-31b7-11e7-95fd-9fa78ff9bbf9.png)

This module should specify a directory and filename, consider adding a button, to do this action.

**Comment by ryanbanderson** [comment]
The idea was that this would be used in conjunction with the module that sets the output path. We could do something like have this one prompt for a path if the output path has not previously been set.

**Comment by ryanbanderson** [comment]
Closing. I think this has been resolved.
