### ISSUE TITLE
Scatter Plot: Coloring returns ValueError

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#179]
In one of the plotting routines (that need to be moved to the GUI side) I have a scatter plot where I color-code the points based on a column of my data. Here's the command in question:
```
mappable = ax1.scatter(x, y, c=np.array(data.df[('comp', colorvar)]), cmap=cmap, linewidth=0.2, edgecolor='Black')
```
This used to work, but now it gives me this error: 
```
ValueError: c of shape (2489,) not acceptable as a color sequence for x with size 2489, y with size 2489
```

**Comment by ryanbanderson** [comment]
This is fixed in this PySAT PR: https://github.com/USGS-Astrogeology/PySAT/pull/98
