### ISSUE TITLE
Repository is huge

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#181]
```
igswzawglt-klvn:repos krodriguez-pr$ du -sh PySAT_Point_Spectra_GUI/
334M	PySAT_Point_Spectra_GUI/
```

At some point some large file(s) were added and then removed from the repo. They are still lingering in the history. I believe the solution is to rebase and force push.

**Comment by tisaconundrum2** [comment]
Should be fixed now
