### ISSUE TITLE
Save and restore using a human-readable file format (.yml?)

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#184]

**Comment by ryanbanderson** [comment]
I'm bumping this up to high. Making it human readable will help a lot with recreating old workflows that may not be compatible when something about the UI or how restore works is changed. You may not be able to just load everything up but at least you can see what was done and re-do it manually in the new version of the GUI.

**Comment by tisaconundrum2** [comment]
Fixed in commit b54a03d

**Comment by tisaconundrum2** [comment]
using `indent=4` as a parameter to `json.dump()` gives us a readable output
