### ISSUE TITLE
Remove auto-generated code

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#185]
There seems to be quite a bit auto-generated GUI code being added to the repo. Should be simple enough to delete the files and have them be generated via setup.py instead during install.

**Comment by tisaconundrum2** [comment]
Agreed!
```
python setup.py clean_ui
python setup.py build_ui
```

**Comment by Kelvinrr** [comment]
closed with #186
