### ISSUE TITLE
[Combine Data Sets] Index needs to be reset to avoid duplicates

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#191]
First, it needs to be fixed so that it works.
Second, it should create a new data set rather than overwriting one of the existing ones.

**Comment by Kelvinrr** [comment]
fixed with #194 re-open if it doesn't solve the problem.

**Comment by ryanbanderson** [comment]
This is not fixed. We don't just want to concatenate onto the existing data set, we want to merge (or something, not sure what exact pandas command will do the trick). Need to look at the actual data before and after to check that this is working.

**Comment by ryanbanderson** [comment]
Actually I may be wrong. Just tried this on a small test case and it seems ok. Need to play around with it some more.

**Comment by ryanbanderson** [comment]
Index needs to be reset to avoid duplicates

**Comment by tisaconundrum2** [comment]
This should be fixed by ignoring the "index" that is included in the files.
Technically this is a non-issue since the existence of the columns doesn't add or take away from the overall data processing
