### ISSUE TITLE
During restore we are losing reference to the datakey

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#200]
![cdcf4b7e-cf87-4b26-87a8-48b073252c32](https://user-images.githubusercontent.com/11879769/35475328-a081bdd4-0359-11e8-9f50-2a219ea4af55.gif)

**Comment by ryanbanderson** [comment]
This looks like two related issues to me. First, the list of data should not go blank in regression Train when the workflow is run: the datakeys should already be there (even if the data isn't) as a result of populating the load data modules.

The second issue is that the X and Y variables depend on reading the currently-selected data to get variables, so when that's empty, there's nothing to put there. If the first issue is fixed, then it should at least not lose all the valid data. The X and Y options could refresh as part of running Regression-Train, keep the correct things selected (if they still exist after potential changes), and if they don't exist, stop the workflow and prompt the user to choose valid X and Y choices.

**Comment by AustinSanders** [comment]
@tisaconundrum2 @ryanbanderson The list of datakeys is currently set when the data name is edited, not when the modules are run.  Given that a restore does not involve an edit, the list upon which the dropdown is dependent is not updated.

This should be a very simple fix and should only involve QTickle calling the setDataKey function whenever a dataset is restored.

**Comment by tisaconundrum2** [comment]
Closing soon, as this has been fixed in my current branch. I will close this when I've pushed to USGS

**Comment by tisaconundrum2** [comment]
Fixed in merge
