### ISSUE TITLE
Issues with restoration

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#211]
- Wavelengths aren't preserved in normalization
- Remove rows settings aren't preserved

Both of these involve initializing the options with data from the existing data set, so may be similar problems. Need a way to tell the UI that we're restoring, so just use the saved values rather than trying to get new ones.

**Comment by tisaconundrum2** [comment]
remove rows works fine when restoring.
the wavelengths are also restoring fine. 
If there is a different unexpected behavior that you are referencing here, please let me know.

Closing as it seems that restoration is working correctly.
