### ISSUE TITLE
Add Clustering Capability

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#217]
Start with K-means from scikit: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans

**Comment by tisaconundrum2** [comment]
Add a new Menu selection and Module with Submodules for User to utilize

**Comment by ryanbanderson** [comment]
I had an hour to spare yesterday, so I implemented K-means on my dev branches. Will add other methods as I have time.

**Comment by ryanbanderson** [comment]
Saving this link here for later reference. How to plot a dendrogram produced by hierarchical clustering: https://github.com/scikit-learn/scikit-learn/blob/70cf4a676caa2d2dad2e3f6e4478d64bcb0506f7/examples/cluster/plot_hierarchical_clustering_dendrogram.py

**Comment by ryanbanderson** [comment]
A couple of clustering methods have been implemented. Closing this and marking it to revisit later.
