### ISSUE TITLE
Unable to load point_spectra_gui

### ISSUE THREAD

**Issue by astroindhu** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#224]
After installing point_spectra_gui through environment.yml, when I run "point_spectra_gui" I am getting the following error.

**You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Available platform plugins are: cocoa, minimal, offscreen.**

Here are the final packages installed under point_spectra_gui conda environment in my system (Mac OS Sierra) 

conda version: conda 4.5.0
python version: Python 3.6.5

installed packages 
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0
certifi                   2018.1.18                py36_0
cycler                    0.10.0           py36hfc81398_0
dbus                      1.13.2               h5243cc1_0
expat                     2.2.5                hb8e80ba_0
freetype                  2.8                  h12048fb_1
gettext                   0.19.8.1             h15daf44_3
glib                      2.53.6               h33f6a65_2
icu                       58.2                 h4b95b61_1
intel-openmp              2018.0.0                      8
jpeg                      9b                   he5867d9_2
kiwisolver                1.0.1            py36h792292d_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1                  hb4e282d_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                 hdd342a3_7
libpng                    1.6.34               he12f830_0
libpysat                  1.2.3                     <pip>
matplotlib                2.2.2            py36ha7267d0_0
mkl                       2018.0.2                      1
mkl_fft                   1.0.1            py36h917ab60_0
mkl_random                1.0.1            py36h78cc56f_0
ncurses                   6.0                  hd04f020_2
numpy                     1.14.2           py36ha9ae307_1
openssl                   1.0.2o               h26aff7b_0
pandas                    0.22.0           py36h0a44026_0
pcre                      8.41                 hfb6ab37_1
pip                       9.0.3                    py36_0
point-spectra-gui         3.4.4                     <pip>
pvl                       0.3.0                     <pip>
pyparsing                 2.2.0            py36hb281f35_0
pyqt                      5.9.2            py36h11d3b92_0
python                    3.6.5                hc167b69_0
python-dateutil           2.7.2                    py36_0
pytz                      2018.3                   py36_0
qt                        5.9.4                h14e15a9_0
Qtickle                   1.5.9                     <pip>
qtmodern                  0.1.4                     <pip>
QtPy                      1.4.0                     <pip>
readline                  7.0                  hc1231fa_4
scikit-learn              0.19.1           py36hffbff8c_0
scipy                     1.0.1            py36hcaad992_0
setuptools                39.0.1                   py36_0
sip                       4.19.8           py36h0a44026_0
six                       1.11.0           py36h0e22d5e_1
sklearn                   0.0                       <pip>
sqlite                    3.22.0               h3efe00b_0
tk                        8.6.7                h35a86e2_3
tornado                   5.0.1                    py36_1
wheel                     0.31.0                   py36_0
xz                        5.2.3                h0278029_2
zlib                      1.2.11               hf3cbc9b_2

Awaiting solutions to fix my installation

**Comment by tisaconundrum2** [comment]
Thank you for sending us this issue.
Quick question, are you using Mac OS?

**Comment by astroindhu** [comment]
Yea ! Mac OS  Sierra 10.12.6. Let me know if you need more info. 

Totally looking forward.

**Comment by tisaconundrum2** [comment]
I think it might be an issue with SQLite. When Qt is installed onto your Mac, some of the Qt binaries might be trying to use the already installed Qt binaries on Mac.

What you can try to do is tell SQLite which Qt binaries to use, this using the install_name_tool program, 

```
$ cd [PathToMyApp]/myApp.app/Contents/Frameworks
$ install_name_tool -change QtCore.framework/Versions/5/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore ../PlugIns/sqldrivers/libqsqlite.dylib
$ install_name_tool -change QtSql.framework/Versions/5/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/5/QtSql ../PlugIns/sqldrivers/libqsqlite.dylib
```

**Comment by astroindhu** [comment]
Aah, Thanks !! - but still getting the same error. 

Here are my actual commands (which ran without any error) 

```
$ cd /Users/vara_id/anaconda/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework
$ install_name_tool -change QtCore.framework/Versions/5/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore ../PlugIns/sqldrivers/libqsqlite.dylib
$ install_name_tool -change QtSql.framework/Versions/5/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/5/QtSql ../PlugIns/sqldrivers/libqsqlite.dylib
```
Here is the same error message

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Available platform plugins are: cocoa, minimal, offscreen.

Reinstalling the application may fix this problem.
[1]    53522 abort      point_spectra_gui

Any other way out ?? looking forward !

**Comment by astroindhu** [comment]
Here is both good and bad news. 

When I followed the same installation procedure in windows - its all succesful. I can launch GUI beautifully. Its neat, thanks ! 

When I removed the installation in my Mac and re-installed the same, I just noticed the warning message which appears before the actual installation starts. Below is the message:

**
╰─ conda env create -n point_spectra_gui -f environment.yml

"/Users/vara_id/anaconda/lib/python3.6/site-packages/conda_env/env.py:68: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel_yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel_yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(yamlstr)"

Fetching package metadata ...............
Solving package specifications: .
** 

At the end of the instatllation I am receiving the same error as before 
"ou might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Available platform plugins are: cocoa, minimal, offscreen.

Reinstalling the application may fix this problem.
[1]    56978 abort      point_spectra_gui" 

Looks like this is something to do with Mac installtion of point_spectra_gui ? 

Mac is my general use system and I have all data in my Mac. It will be nice to get this fixed in my Mac. 

On a happy note - I could still use pysat - normal python mode :) 

Looking forward !

**Comment by tisaconundrum2** [comment]
Thank you very much for this information! 
I know this is probably not the most elegant, but here's my quick shortstop solution for you. Unless @ryanbanderson or someone else finds a better solution.

Using a VM (Virtual Box) try installing Linux, (Mint or Ubuntu are two of my favorite distros) and see if you can install our application through this. You'll be able to drop and drag your data in the VM.
Our application is still in development, but we will push out a more robust version for Mac as soon as possible and you'll be the first to be notified.

**Comment by astroindhu** [comment]
Hi --- here is the update !! There is no bug with the point_spectra_gui -Mac installation at all. After playing with it, I finally realized that qt binary used by my USGS ISIS3 installation clashes with qt binary of conda installation. In my zsh profile I have wrote it by default that it should start ISISROOT when zsh starts. After commenting those lines, now I can launch point_spectra_gui without any problem :) 

However, I just get these warnings when I load point_spectra_gui in my Mac - but I dont get such warning in my windows installation

**/Users/vara_id/anaconda/envs/point_spectra_gui/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/vara_id/anaconda/envs/point_spectra_gui/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
QLayout: Attempting to add QLayout "" to QWidget "loadData", which already has a layout**

 Maybe this is helpful for your future release ! 

Thanks a lot for all the efforts 

I guess you can close this thread :)

**Comment by tisaconundrum2** [comment]
Thank @jlaura that's super useful!
@astroindhu I'm glad it's working for you now. The QLayout is a known bug. It will not break your gui

**Comment by astroindhu** [comment]
@jlaura Aahh !! Thanks for the tip !! Here is what I finally did now. 

**Earlier:** I was activating ISIS3 by default everytime I launched a new zsh window by adding the following lines in my ~/.zshrc profile 
```
ISISROOT=/Users/vara_id/isis3/isis/ 
export ISISROOT; 
. $ISISROOT/scripts/isis3Startup.sh
```
This therefore activated isis3 before I even activate my conda env. 

**Tried:** When I added source activate point_spectra_gui by default before the isis3 activation lines before in my .zshrc showed the same Qt binary error. 

**Now:** I just created a isis3 () inside my  ~/.zshrc such that so that I only activate ISIS3 if I run isis3 in my shell. 

```
isis3 () { 
ISISROOT=/Users/vara_id/isis3/isis/ 
export ISISROOT; 
. $ISISROOT/scripts/isis3Startup.sh
}
```
Now, I can run point_spectra_gui smoothly until I call isis3. 

ISIS3 is not showing any error even if I activate point_spectra_gui or not. But point_spectra_gui fails to load the moment I call isis3. Head scratcher ! -- something to be solved in future release ? 

@tisaconundrum2 Thanks a lot for the tips and help :) I am glad indeed. Yet to explore the gui - but I am currently adding new functions/classes inside my forked usgs/pysat explicitly to read/plot/analyse our PSL spectra. stay tuned !! 

Coming to PSIDA ? I will be there - I can show you the package I am developing (PlanetSpec) - which I am trying to merge it with pysat to support the planetary spectrscopy community :) -- fingers crossed !

**Comment by tisaconundrum2** [comment]
@astroindhu That is an interesting bug, thank you for your thorough input, this will be useful for the future.

**Comment by ryanbanderson** [comment]
@astroindhu I will be at PSIDA, as will @jlaura. It would be great to meet in person and discuss spectroscopy tools!

**Comment by astroindhu** [comment]
@ryanbanderson Perfect! More spectroscopy at PSIDA then! Will find you and @jlaura there.
