### ISSUE TITLE
File selection dialog opens repeatedly

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#228]
In modules where the user has to choose a file, something is happening with the file selection dialog, causing it to open multiple times in a row.

**Comment by tisaconundrum2** [comment]
This seems to have something to do with `Refresh Modules`.
Looking further into it

**Comment by ryanbanderson** [comment]
I figured this out! It is because Qt can connect functions automatically if they are named with a certain format. When we name a function with that format, and then also explicitly connect it, it gets called twice. See this StackOverflow question: https://stackoverflow.com/questions/30430063/qtoolbutton-released-signal-fired-twice

**Comment by ryanbanderson** [comment]
Ok, I think the problem is that clicking refresh re-runs connectwidgets, which creates duplicate connections.

**Comment by tisaconundrum2** [comment]
The solution was to disconnect the push button prior to the connect. This way we aren't recalling our connection.

Feel free to reference this stackoverflow question
https://stackoverflow.com/questions/3530590/qt-signals-and-slot-connected-twice-what-happens#_=_
This is a known problem with Qt's connect. But unfortunately there exists no python equivalent of Qt::UniqueConnection

Instead I just updated Qtickle to include a disconnect method for push buttons. This of course is not limited to push buttons and we can add other UI components in the future, but for this particular instance push buttons were a problem.
