### ISSUE TITLE
Prevent restore from working if the main window is not empty

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#235]
If I restore the "Load Data" module as the first module, it does ok. But if I do other stuff and then restore it, it comes up blank:

![image](https://user-images.githubusercontent.com/3344800/39195664-e8751bc8-47a5-11e8-8369-eebbc1a77d56.png)

**Comment by tisaconundrum2** [comment]
This is expected behavior. You cannot restore a module on top of an already loaded module.
Unless I'm understanding something wrong here.

**Comment by ryanbanderson** [comment]
It's not "on top of" the loaded module (not sure what that would mean). In the example on the right, I started a new workflow, ran some other modules, and then tried to restore a saved workflow with the Load Data module in it, but it comes up empty.

**Comment by tisaconundrum2** [comment]
Yeah, that's what I suspected you tried to do. 
So if i'm understanding you correctly. It looks roughly like this.
```
Workflow1
[load data]

Workflow2
[content1]
[content2]
[content3]
[load data] # from Workflow1
```

However, it doesn't quite work like that.
`[load data] # from Workflow1` will actually try to restore itself on top of `[content1]`

**Comment by ryanbanderson** [comment]
Ok, in that case we should prevent restore from working unless the main window is empty

**Comment by ryanbanderson** [comment]
I implemented this in my dev branch, so this issue will be resolved by the next pull request.
