### ISSUE TITLE
Add ability to read ChemCam PDS-format Experimental Data Records

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#33]

**Comment by tisaconundrum2** [comment]
EDR is: experimental data record

**Comment by ryanbanderson** [comment]
EDR data is available here: http://pds-geosciences.wustl.edu/msl/msl-m-chemcam-libs-2-edr-v1/mslccm_0xxx/data/

We want to be able to read the "cl5*.dat" (LIBS spectra) and "cl9*.dat" (dark spectra) files.

The PyPDS library might be helpful: https://github.com/RyanBalfanz/PyPDS

**Comment by ryanbanderson** [comment]
ChemCam observation metadata is available here: http://pds-geosciences.wustl.edu/msl/msl-m-chemcam-libs-4_5-rdr-v1/mslccm_1xxx/document/msl_ccam_obs.csv

**Comment by tisaconundrum2** [comment]
Time Chart for completion
<pre>
[-]                        1 days research
   [----]                  4 days development
         [-----]           5 days testing

</pre>

**Comment by tisaconundrum2** [comment]
PyPDS never got updated to Python 3. I will try and fix this and see where this gets me.

**Comment by tisaconundrum2** [comment]
If I can't get PDS fixed, I'll need to push my research time out a little bit.

**Comment by ryanbanderson** [comment]
I asked on the OpenPlanetary slack to see if there are any better options out there for reading PDS .dat files. (You should join: http://openplanetary.co/)

**Comment by ryanbanderson** [comment]
Some suggestions that I've gotten:
https://github.com/planetarypy/planetaryimage
https://github.com/cmillion/pds-util/blob/master/src/pds.py

**Comment by ryanbanderson** [comment]
This might help too: https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.fromfile.html

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/27359576-55f92d1e-55d1-11e7-846d-95e0d99c5753.png)
This is our section of interest.

The `START_BYTE` is 1
The End `BYTE` is 12888

**Comment by tisaconundrum2** [comment]
psuedocode:

Look for an `OBJECT`
is the name `"CCAM_LIBS_DATA_CONTAINER"`
find `START_BYTE` 
if next line is not `END_OBJECT`: continue looking

**Comment by tisaconundrum2** [comment]
I'm thinking if these are stored numbers. We'll need to convert the byte values to decimal. And then we can split and plot?

**Comment by ryanbanderson** [comment]
This doesn't really have anything to do with plotting. We just need to get the data into the Pandas format that PySAT likes, then we can do whatever we want to it, including plotting.

**Comment by tisaconundrum2** [comment]
Each of the three parts of the spectrum file consist of an integral number of “records”, where the record size is the size needed to contain one spectrum.

![image](https://user-images.githubusercontent.com/11879769/27454522-0734251a-574f-11e7-9c31-f0a3cf6c0ae2.png)

4.3.2.2 LIBS Spectrum EDR
The binary content of the LIBS spectrum EDR is comprised of intensity values, or data numbers
(DNs). Depending on which of the three variants of spectroscopy activity were commanded, the
values fall somewhere within the stored 16-bit or 32-bit data range. Unlike the RMI image data, LIBS
spectrum data are only returned as uncompressed.

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/27457713-91987a8e-575a-11e7-8d51-68e024bafb55.png)

**Comment by tisaconundrum2** [comment]
From the lbl file
![image](https://user-images.githubusercontent.com/11879769/27502088-6849d412-5826-11e7-9bde-80adcc561c94.png)
we have the ability to get header file's byte size!
![image](https://user-images.githubusercontent.com/11879769/27502102-7c82775e-5826-11e7-968f-10b8bbadfa0e.png)

with this in mind, we can `seek()` through our `*.dat` file and get the necessary bytes we care about

**Comment by tisaconundrum2** [comment]
@ryanbanderson 
do these numbers look right to you?
![image](https://user-images.githubusercontent.com/11879769/27502344-27451416-5828-11e7-8e8c-52175d95a926.png)

**Comment by tisaconundrum2** [comment]
These don't look right to me, so I'm going to try and convert them down to float32

**Comment by tisaconundrum2** [comment]
@ryanbanderson 
Ok, I was able to figure everything out. But please double check on these numbers.
First off, Everything needs to be in float16 as it is 2 bytes of information. you can see that in the `nbytes` variable.
Secondly, I needed to set the starting and ending byte correctly. Here are the first 30 hits. What do you think?

![image](https://user-images.githubusercontent.com/11879769/27503251-68bdce2c-582f-11e7-895b-dbf475399ae8.png)

**Comment by ryanbanderson** [comment]
Those values seem small but might be ok. I'd have to see them plotted as
spectra to judge.


Ryan Anderson
Physical Scientist / Developer
USGS Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001
Cell: 734-657-8085
Office: 928-556-7239
rbanderson@usgs.gov

**Comment by ryanbanderson** [comment]
Remember you can compare the EDR with the equivalent CCS (which is on PDS
as .csv). The values won't be exactly the same but you can plot them both
and the EDR should look similar to the CCS (but without the continuum
removed)

Also, your screenshot above looks like it has 96660 elements, which works
out to 15 x 6444 and unless you happen to be trying to read an observation
with 15 spectra, it's more likely that you should be getting 30 x 6444
elements. (checking the matching ccs file, or looking it up in the metadata
list
<http://pds-geosciences.wustl.edu/msl/msl-m-chemcam-libs-4_5-rdr-v1/mslccm_1xxx/document/msl_ccam_obs.csv>can
help you determine how many shots for the observation you're looking at)


Ryan Anderson
Physical Scientist / Developer
USGS Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001
Cell: 734-657-8085
Office: 928-556-7239
rbanderson@usgs.gov

**Comment by tisaconundrum2** [comment]
Thanks Ryan, that helps a lot :)

**Comment by tisaconundrum2** [comment]
I've plotted the points and this is what was returned 
![image](https://user-images.githubusercontent.com/11879769/27563059-4e2d74ac-5a84-11e7-8897-7b64e1a5add8.png)
What is your opinion of it?

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/27563294-a6cd76ba-5a85-11e7-828d-e9f84eca5647.png)
I plotted the RDR file, but I'm not sure if that is a good file to measure up against.

**Comment by ryanbanderson** [comment]
This is looking closer. My first thoughts are: 1. That looks like a dark
spectrum rather than an active LIBS spectrum, so make sure you're reading a
CL5 and not a CL9 file. 2. Those spikes are obviously anomalous.

If you are really reading a CL5 file, I'd recommend trying a different one
from a different sol in case that one happens to be a bad observation. If
you get something looking similar (broad lumpy spectrum with no obvious
emission lines on top of it) then you may have to read in the CL9 EDR as
well and subtract it from the CL5 EDR to get a good comparison with the RDR.


Ryan Anderson
Physical Scientist / Developer
USGS Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001
Cell: 734-657-8085
Office: 928-556-7239
rbanderson@usgs.gov

**Comment by ryanbanderson** [comment]
For reference, here is what an EDR looks like when plotted with one of the ChemCam tools (note that this is plotted vs wavelength so may be out of order as compared to your raw plots vs bin #):
![image](https://user-images.githubusercontent.com/3344800/27571808-fc8c22ea-5abc-11e7-8f16-0d28256554df.png)

**Comment by tisaconundrum2** [comment]
More information on SIS and data
http://pds-geosciences.wustl.edu/msl/msl-m-chemcam-libs-2-edr-v1/mslccm_0xxx/catalog/ccam_rmi_edr_ds.cat

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/27661396-fcd88c22-5c0e-11e7-9ffb-04fded7a0793.png)
![image](https://user-images.githubusercontent.com/11879769/27661404-02779e48-5c0f-11e7-9fc4-ef65f157ab3c.png)
