### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#38]
This happens occasionally, possibly related to running in PyCharm?

**Comment by ryanbanderson** [comment]
I'm getting this error a lot when running a restored workflow and deleting a module before running.

**Comment by tisaconundrum2** [comment]
Sounds like a memory allocation problem. I'll look into it

**Comment by ryanbanderson** [comment]
Also seems to be more common when running in debug mode.

**Comment by tisaconundrum2** [comment]
I'll try playing around with it in both debug and non debug mode. 
Does this happen with particular Modules or randomly?

**Comment by ryanbanderson** [comment]
This bug is still happening from time to time. Really annoying when it happens in the middle of a long, complicated workflow!!

**Comment by tisaconundrum2** [comment]
This might be part of the problem
https://stackoverflow.com/questions/28447567/python-terminates-process-with-exit-code-1073741819

**Comment by tisaconundrum2** [comment]
> I figured out what the issue was. There were values in the CSV like that were not being properly read by the parser. I changed the code from
> 
> `frame.from_csv('c:/Nitin/692/Python/CSV/21LIVvTOT_user_geo_Reply.csv', header=True)`
> to
> 
> `data = pandas.read_csv('c:/Nitin/692/Python/CSV/21LIVvTOT_user_geo_Reply.csv', encoding='latin-1', engine='python')`
> Guess the encoding in `utf-8` was causing the problem. The code ran when I changed it to `latin-1`.

**Comment by ryanbanderson** [comment]
Just got it again when I tried to scroll down to see how far a workflow had gotten. So, it's not just a CSV reading issue.

**Comment by tisaconundrum2** [comment]
Hmmm. I wonder if it's a memory overflow problem

**Comment by ryanbanderson** [comment]
Getting this regularly when debugging submodel predict.

**Comment by ryanbanderson** [comment]
This error also seems to occur frequently when PySAT reaches the end of a workflow.

**Comment by tisaconundrum2** [comment]
I'm becoming more convinced that this is bad access in memory. I'm thinking that something is trying to access something that no longer exists. I have a feeling that it has something to do with our `list_of_modules`

I'm pretty sure our newer iteration will fix this. We are no longer writing to a giant list; and instead everything remains static in one location.

**Comment by Tehsurfer** [comment]
Did updating your list_of_modules end up fixing the error?

**Comment by ryanbanderson** [comment]
It's been a while since this was closed, but I think so. I just encountered this error again the other day when trying to implement a progress bar in multiple separate parts of the UI. My best guess in this new case is that the progress bars are somehow pointing to the same place in memory and conflicting with each other. Probably time to get better at using threading...

**Comment by mapfiable** [comment]
I am also experiencing this issue and I may or may not have accidentally found some code to reproduce it, although I haven't confirmed it on a second machine yet. This is what produces the error for me:
```
import sys
import matplotlib.pyplot as plt

from PyQt5.QtWidgets import QDialog, QApplication


class MainWindow(QDialog):
    def __init__(self):
        super().__init__()
        fig, ax = plt.subplots()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    GUI = MainWindow()
    GUI.show()
    sys.exit(app.exec_())
```
This also produces `QPaintDevice::metrics: Device has no metric information` three times. In order to stop the issue, you can either comment out `fig, ax = plt.subplots()` or `app = QApplication(sys.argv)`, but of course this stops me from what I am trying to do. I can confirm this using PyCharm but not with Spyder.

**Comment by lapvv** [comment]
Try to run as administrator Idea or MS VSC or other app which you use.
I had the same trouble on Win 10 and it helped, whereas I hadn't it on Win7.
