### ISSUE TITLE
Add .travis.yml for daily code testing and coverage

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#49]

**Comment by tisaconundrum2** [comment]
How to add Coverage on UI pieces
![image](https://user-images.githubusercontent.com/11879769/27362470-63231b96-55e3-11e7-9e4f-5405db5b7ff4.png)
We simply check to see if the necessary components were loaded in, correctly.

**Comment by tisaconundrum2** [comment]
Refer to this test file for more information on how to deal with the UI
https://github.com/planetarypy/pdsview/blob/master/tests/test_band_widget.py

**Comment by tisaconundrum2** [comment]
In theory, we could actually instantiate an entire workflow and then test it.
We can also test the restoration process in the same way.

This will also make us more cognizant of our code-base as we add more features and test their restorability.

**Comment by tisaconundrum2** [comment]
Testing workflows

Load Data Set 1
Load Data Set 2
Interpolate Data Set 2 onto Data Set 1
Mask Data Set 1 and 2
Normalize Data Set 1 and 2
Strat Folds Data Set 1
CV Data Set 1 - Train (PLS, nc=1-10)
Plot RMSECV vs # of components from the CV Results
Export CV Results to .csv
Train PLS on Data Set 1 - Train (nc=6)
Predict Data Set 1 - Test
Predict Data Set 2
Plot Data Set 1 - Test predictions on 1 to 1 plot
Plot Data Set 2 predictions on the same plot

Load data set (the JSC data is good for this since it is not already baseline corrected)
Mask
Baseline Removal (AirPLS)
Plot Spectra - Original data set - pick a spectrum based on target name
Plot Spectra - Baseline for the same spectrum on the same plot, but different color

Load Data Set
Mask Data Set
Normalize Data Set
Strat Folds Data Set
Train PLS on Data Set - Train (nc=6, 0-100%)
Train PLS on Data Set - Train (nc=7, 60-100%)
Train PLS on Data Set - Train (nc=5, 30-70%)
Train PLS on Data Set - Train (nc=4, 0-40%)
Train Lasso on Data Set - Train (use CV optimization)
Submodel predict Data set - Test using PLS 0-100% as reference, 0-40 as low, 30-70 as mid, 60-100 as high model
Predict Data Set - Test using Lasso
Plot both predictions on 1 to 1 plot

**Comment by Kelvinrr** [comment]
I imagine this is closed with PR #182 and #183
