### ISSUE TITLE
Test full workflows and find errors

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#56]

**Comment by tisaconundrum2** [comment]
Testing workflows

Load Data Set 1
Load Data Set 2
Interpolate Data Set 2 onto Data Set 1
Mask Data Set 1 and 2
Normalize Data Set 1 and 2
Strat Folds Data Set 1
CV Data Set 1 - Train (PLS, nc=1-10)
Plot RMSECV vs # of components from the CV Results
Export CV Results to .csv
Train PLS on Data Set 1 - Train (nc=6)
Predict Data Set 1 - Test
Predict Data Set 2
Plot Data Set 1 - Test predictions on 1 to 1 plot
Plot Data Set 2 predictions on the same plot

Load data set (the JSC data is good for this since it is not already baseline corrected)
Mask
Baseline Removal (AirPLS)
Plot Spectra - Original data set - pick a spectrum based on target name
Plot Spectra - Baseline for the same spectrum on the same plot, but different color

Load Data Set
Mask Data Set
Normalize Data Set
Strat Folds Data Set
Train PLS on Data Set - Train (nc=6, 0-100%)
Train PLS on Data Set - Train (nc=7, 60-100%)
Train PLS on Data Set - Train (nc=5, 30-70%)
Train PLS on Data Set - Train (nc=4, 0-40%)
Train Lasso on Data Set - Train (use CV optimization)
Submodel predict Data set - Test using PLS 0-100% as reference, 0-40 as low, 30-70 as mid, 60-100 as high model
Predict Data Set - Test using Lasso
Plot both predictions on 1 to 1 plot

**Comment by ryanbanderson** [comment]
Closing this as too vague to be useful. We should always be doing this, it doesn't need to be listed as an issue.
