### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#6]
- The links in the wiki install instructions don't lead to Anaconda 4.1.1 downloads, they just point back to the wiki
- The instructions say to do python setup.py install in PySAT, but PySAT doesn't have a setup.py
- When trying to run using 'python point_spectra_gui', I get the error: "can't find '__main__' module in point_spectra_gui"

**Comment by tisaconundrum2** [comment]
- [ ] Fix link to Anaconda downloads
- [ ] Add setup.py
- [ ] Fix point_spectra_gui's missing __main__ module

**Comment by tisaconundrum2** [comment]
Everything should be fixed now.
