### ISSUE TITLE
Add ability to delete/insert modules in the middle of a workflow

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#64]
As I start to actually use the tool, I keep finding that this would be very useful.

**Comment by tisaconundrum2** [comment]
Definitely will try to get this working too. 
I will need to research how layouts are actually working in Qt.
I could also potentially create a gridLayout and have each one numbered. So as to allow for locality within the UI

**Comment by ryanbanderson** [comment]
The more I use the tool, the more I see how useful this capability would be, so I increased the priority.

**Comment by tisaconundrum2** [comment]
First proposed idea of how to insert new modules into a certain point
![untitled diagram](https://user-images.githubusercontent.com/11879769/37435989-046e4ade-27a3-11e8-8bc1-c0b660981505.png)

**Comment by tisaconundrum2** [comment]
Working correctly
