### ISSUE TITLE
Implement additional regression methods from scikit-learn in regression_train

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#65]
This should be pretty straightforward. We just need to make the interface for each of these so it can pop up when selected and pass the parameters the same way we've been doing for other scikit regression methods.

- [x] Elastic Net (highest priority)
- [x] Ridge Regression
- [x] Lasso LARS
- [x] Bayesian Ridge Regression
<table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><p class="first"><strong>n_iter</strong> : int, optional</p>
<blockquote>
<div><p>Maximum number of iterations.  Default is 300.</p>
</div></blockquote>
<p><strong>tol</strong> : float, optional</p>
<blockquote>
<div><p>Stop the algorithm if w has converged. Default is 1.e-3.</p>
</div></blockquote>
<p><strong>alpha_1</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : shape parameter for the Gamma distribution prior
over the alpha parameter. Default is 1.e-6</p>
</div></blockquote>
<p><strong>alpha_2</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : inverse scale parameter (rate parameter) for the
Gamma distribution prior over the alpha parameter.
Default is 1.e-6.</p>
</div></blockquote>
<p><strong>lambda_1</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : shape parameter for the Gamma distribution prior
over the lambda parameter. Default is 1.e-6.</p>
</div></blockquote>
<p><strong>lambda_2</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : inverse scale parameter (rate parameter) for the
Gamma distribution prior over the lambda parameter.
Default is 1.e-6</p>
</div></blockquote>
<p><strong>compute_score</strong> : boolean, optional</p>
<blockquote>
<div><p>If True, compute the objective function at each step of the model.
Default is False</p>
</div></blockquote>
<p><strong>fit_intercept</strong> : boolean, optional</p>
<blockquote>
<div><p>whether to calculate the intercept for this model. If set
to false, no intercept will be used in calculations
(e.g. data is expected to be already centered).
Default is True.</p>
</div></blockquote>
<p><strong>normalize</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>If True, the regressors X will be normalized before regression.
This parameter is ignored when <cite>fit_intercept</cite> is set to False.
When the regressors are normalized, note that this makes the
hyperparameters learnt more robust and almost independent of the number
of samples. The same property is not valid for standardized data.
However, if you wish to standardize, please use
<cite>preprocessing.StandardScaler</cite> before calling <cite>fit</cite> on an estimator
with <cite>normalize=False</cite>.</p>
</div></blockquote>
<p><strong>copy_X</strong> : boolean, optional, default True</p>
<blockquote>
<div><p>If True, X will be copied; else, it may be overwritten.</p>
</div></blockquote>
<p><strong>verbose</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>Verbose mode when fitting the model.</p>
</div></blockquote>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Attributes:</th><td class="field-body"><p class="first"><strong>coef_</strong> : array, shape = (n_features)</p>
<blockquote>
<div><p>Coefficients of the regression model (mean of distribution)</p>
</div></blockquote>
<p><strong>alpha_</strong> : float</p>
<blockquote>
<div><p>estimated precision of the noise.</p>
</div></blockquote>
<p><strong>lambda_</strong> : float</p>
<blockquote>
<div><p>estimated precision of the weights.</p>
</div></blockquote>
<p><strong>scores_</strong> : float</p>
<blockquote class="last">
<div><p>if computed, value of the objective function (to be maximized)</p>
</div></blockquote>
</td>
</tr>
</tbody>
</table>

- [x] Automatic Relevance Determination
<table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><p class="first"><strong>n_iter</strong> : int, optional</p>
<blockquote>
<div><p>Maximum number of iterations. Default is 300</p>
</div></blockquote>
<p><strong>tol</strong> : float, optional</p>
<blockquote>
<div><p>Stop the algorithm if w has converged. Default is 1.e-3.</p>
</div></blockquote>
<p><strong>alpha_1</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : shape parameter for the Gamma distribution prior
over the alpha parameter. Default is 1.e-6.</p>
</div></blockquote>
<p><strong>alpha_2</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : inverse scale parameter (rate parameter) for the
Gamma distribution prior over the alpha parameter. Default is 1.e-6.</p>
</div></blockquote>
<p><strong>lambda_1</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : shape parameter for the Gamma distribution prior
over the lambda parameter. Default is 1.e-6.</p>
</div></blockquote>
<p><strong>lambda_2</strong> : float, optional</p>
<blockquote>
<div><p>Hyper-parameter : inverse scale parameter (rate parameter) for the
Gamma distribution prior over the lambda parameter. Default is 1.e-6.</p>
</div></blockquote>
<p><strong>compute_score</strong> : boolean, optional</p>
<blockquote>
<div><p>If True, compute the objective function at each step of the model.
Default is False.</p>
</div></blockquote>
<p><strong>threshold_lambda</strong> : float, optional</p>
<blockquote>
<div><p>threshold for removing (pruning) weights with high precision from
the computation. Default is 1.e+4.</p>
</div></blockquote>
<p><strong>fit_intercept</strong> : boolean, optional</p>
<blockquote>
<div><p>whether to calculate the intercept for this model. If set
to false, no intercept will be used in calculations
(e.g. data is expected to be already centered).
Default is True.</p>
</div></blockquote>
<p><strong>normalize</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>If True, the regressors X will be normalized before regression.
This parameter is ignored when <cite>fit_intercept</cite> is set to False.
When the regressors are normalized, note that this makes the
hyperparameters learnt more robust and almost independent of the number
of samples. The same property is not valid for standardized data.
However, if you wish to standardize, please use
<cite>preprocessing.StandardScaler</cite> before calling <cite>fit</cite> on an estimator
with <cite>normalize=False</cite>.</p>
</div></blockquote>
<p><strong>copy_X</strong> : boolean, optional, default True.</p>
<blockquote>
<div><p>If True, X will be copied; else, it may be overwritten.</p>
</div></blockquote>
<p><strong>verbose</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>Verbose mode when fitting the model.</p>
</div></blockquote>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Attributes:</th><td class="field-body"><p class="first"><strong>coef_</strong> : array, shape = (n_features)</p>
<blockquote>
<div><p>Coefficients of the regression model (mean of distribution)</p>
</div></blockquote>
<p><strong>alpha_</strong> : float</p>
<blockquote>
<div><p>estimated precision of the noise.</p>
</div></blockquote>
<p><strong>lambda_</strong> : array, shape = (n_features)</p>
<blockquote>
<div><p>estimated precisions of the weights.</p>
</div></blockquote>
<p><strong>sigma_</strong> : array, shape = (n_features, n_features)</p>
<blockquote>
<div><p>estimated variance-covariance matrix of the weights</p>
</div></blockquote>
<p><strong>scores_</strong> : float</p>
<blockquote class="last">
<div><p>if computed, value of the objective function (to be maximized)</p>
</div></blockquote>
</td>
</tr>
</tbody>
</table>

- [x] Least Angle Regression (LARS)
<table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><p class="first"><strong>n_nonzero_coefs</strong> : int, optional</p>
<blockquote>
<div><p>Target number of non-zero coefficients. Use <code class="docutils literal"><span class="pre">np.inf</span></code> for no limit.</p>
</div></blockquote>
<p><strong>fit_intercept</strong> : boolean</p>
<blockquote>
<div><p>Whether to calculate the intercept for this model. If set
to false, no intercept will be used in calculations
(e.g. data is expected to be already centered).</p>
</div></blockquote>
<p><strong>positive</strong> : boolean (default=False)</p>
<blockquote>
<div><p>Restrict coefficients to be &gt;= 0. Be aware that you might want to
remove fit_intercept which is set True by default.</p>
</div></blockquote>
<p><strong>verbose</strong> : boolean or integer, optional</p>
<blockquote>
<div><p>Sets the verbosity amount</p>
</div></blockquote>
<p><strong>normalize</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>If True, the regressors X will be normalized before regression.
This parameter is ignored when <cite>fit_intercept</cite> is set to False.
When the regressors are normalized, note that this makes the
hyperparameters learnt more robust and almost independent of the number
of samples. The same property is not valid for standardized data.
However, if you wish to standardize, please use
<cite>preprocessing.StandardScaler</cite> before calling <cite>fit</cite> on an estimator
with <cite>normalize=False</cite>.</p>
</div></blockquote>
<p><strong>precompute</strong> : True | False | ‘auto’ | array-like</p>
<blockquote>
<div><p>Whether to use a precomputed Gram matrix to speed up
calculations. If set to <code class="docutils literal"><span class="pre">'auto'</span></code> let us decide. The Gram
matrix can also be passed as argument.</p>
</div></blockquote>
<p><strong>copy_X</strong> : boolean, optional, default True</p>
<blockquote>
<div><p>If <code class="docutils literal"><span class="pre">True</span></code>, X will be copied; else, it may be overwritten.</p>
</div></blockquote>
<p><strong>eps</strong> : float, optional</p>
<blockquote>
<div><p>The machine-precision regularization in the computation of the
Cholesky diagonal factors. Increase this for very ill-conditioned
systems. Unlike the <code class="docutils literal"><span class="pre">tol</span></code> parameter in some iterative
optimization-based algorithms, this parameter does not control
the tolerance of the optimization.</p>
</div></blockquote>
<p><strong>fit_path</strong> : boolean</p>
<blockquote>
<div><p>If True the full path is stored in the <code class="docutils literal"><span class="pre">coef_path_</span></code> attribute.
If you compute the solution for a large problem or many targets,
setting <code class="docutils literal"><span class="pre">fit_path</span></code> to <code class="docutils literal"><span class="pre">False</span></code> will lead to a speedup, especially
with a small alpha.</p>
</div></blockquote>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Attributes:</th><td class="field-body"><p class="first"><strong>alphas_</strong> : array, shape (n_alphas + 1,) | list of n_targets such arrays</p>
<blockquote>
<div><p>Maximum of covariances (in absolute value) at each iteration.         <code class="docutils literal"><span class="pre">n_alphas</span></code> is either <code class="docutils literal"><span class="pre">n_nonzero_coefs</span></code> or <code class="docutils literal"><span class="pre">n_features</span></code>,         whichever is smaller.</p>
</div></blockquote>
<p><strong>active_</strong> : list, length = n_alphas | list of n_targets such lists</p>
<blockquote>
<div><p>Indices of active variables at the end of the path.</p>
</div></blockquote>
<p><strong>coef_path_</strong> : array, shape (n_features, n_alphas + 1)         | list of n_targets such arrays</p>
<blockquote>
<div><p>The varying values of the coefficients along the path. It is not
present if the <code class="docutils literal"><span class="pre">fit_path</span></code> parameter is <code class="docutils literal"><span class="pre">False</span></code>.</p>
</div></blockquote>
<p><strong>coef_</strong> : array, shape (n_features,) or (n_targets, n_features)</p>
<blockquote>
<div><p>Parameter vector (w in the formulation formula).</p>
</div></blockquote>
<p><strong>intercept_</strong> : float | array, shape (n_targets,)</p>
<blockquote>
<div><p>Independent term in decision function.</p>
</div></blockquote>
<p><strong>n_iter_</strong> : array-like or int</p>
<blockquote class="last">
<div><p>The number of iterations taken by lars_path to find the
grid of alphas for each target.</p>
</div></blockquote>
</td>
</tr>
</tbody>
</table>

- [x] Support Vector Regression
<table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><p class="first"><strong>C</strong> : float, optional (default=1.0)</p>
<blockquote>
<div><p>Penalty parameter C of the error term.</p>
</div></blockquote>
<p><strong>epsilon</strong> : float, optional (default=0.1)</p>
<blockquote>
<div><p>Epsilon in the epsilon-SVR model. It specifies the epsilon-tube
within which no penalty is associated in the training loss function
with points predicted within a distance epsilon from the actual
value.</p>
</div></blockquote>
<p><strong>kernel</strong> : string, optional (default=’rbf’)</p>
<blockquote>
<div><p>Specifies the kernel type to be used in the algorithm.
It must be one of ‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’ or
a callable.
If none is given, ‘rbf’ will be used. If a callable is given it is
used to precompute the kernel matrix.</p>
</div></blockquote>
<p><strong>degree</strong> : int, optional (default=3)</p>
<blockquote>
<div><p>Degree of the polynomial kernel function (‘poly’).
Ignored by all other kernels.</p>
</div></blockquote>
<p><strong>gamma</strong> : float, optional (default=’auto’)</p>
<blockquote>
<div><p>Kernel coefficient for ‘rbf’, ‘poly’ and ‘sigmoid’.
If gamma is ‘auto’ then 1/n_features will be used instead.</p>
</div></blockquote>
<p><strong>coef0</strong> : float, optional (default=0.0)</p>
<blockquote>
<div><p>Independent term in kernel function.
It is only significant in ‘poly’ and ‘sigmoid’.</p>
</div></blockquote>
<p><strong>shrinking</strong> : boolean, optional (default=True)</p>
<blockquote>
<div><p>Whether to use the shrinking heuristic.</p>
</div></blockquote>
<p><strong>tol</strong> : float, optional (default=1e-3)</p>
<blockquote>
<div><p>Tolerance for stopping criterion.</p>
</div></blockquote>
<p><strong>cache_size</strong> : float, optional</p>
<blockquote>
<div><p>Specify the size of the kernel cache (in MB).</p>
</div></blockquote>
<p><strong>verbose</strong> : bool, default: False</p>
<blockquote>
<div><p>Enable verbose output. Note that this setting takes advantage of a
per-process runtime setting in libsvm that, if enabled, may not work
properly in a multithreaded context.</p>
</div></blockquote>
<p><strong>max_iter</strong> : int, optional (default=-1)</p>
<blockquote>
<div><p>Hard limit on iterations within solver, or -1 for no limit.</p>
</div></blockquote>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Attributes:</th><td class="field-body"><p class="first"><strong>support_</strong> : array-like, shape = [n_SV]</p>
<blockquote>
<div><p>Indices of support vectors.</p>
</div></blockquote>
<p><strong>support_vectors_</strong> : array-like, shape = [nSV, n_features]</p>
<blockquote>
<div><p>Support vectors.</p>
</div></blockquote>
<p><strong>dual_coef_</strong> : array, shape = [1, n_SV]</p>
<blockquote>
<div><p>Coefficients of the support vector in the decision function.</p>
</div></blockquote>
<p><strong>coef_</strong> : array, shape = [1, n_features]</p>
<blockquote>
<div><p>Weights assigned to the features (coefficients in the primal
problem). This is only available in the case of a linear kernel.</p>
<p><cite>coef_</cite> is readonly property derived from <cite>dual_coef_</cite> and
<cite>support_vectors_</cite>.</p>
</div></blockquote>
<p><strong>intercept_</strong> : array, shape = [1]</p>
<blockquote>
<div><p>Constants in decision function.</p>
</div></blockquote>
<p><strong>sample_weight</strong> : array-like, shape = [n_samples]</p>
<blockquote class="last">
<div><p>Individual weights for each sample</p>
</div></blockquote>
</td>
</tr>
</tbody>
</table>

- [x] Kernel Ridge Regression
<table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><p class="first"><strong>alpha</strong> : {float, array-like}, shape = [n_targets]</p>
<blockquote>
<div><p>Small positive values of alpha improve the conditioning of the problem
and reduce the variance of the estimates.  Alpha corresponds to
<code class="docutils literal"><span class="pre">(2*C)^-1</span></code> in other linear models such as LogisticRegression or
LinearSVC. If an array is passed, penalties are assumed to be specific
to the targets. Hence they must correspond in number.</p>
</div></blockquote>
<p><strong>kernel</strong> : string or callable, default=”linear”</p>
<blockquote>
<div><p>Kernel mapping used internally. A callable should accept two arguments
and the keyword arguments passed to this object as kernel_params, and
should return a floating point number.</p>
</div></blockquote>
<p><strong>gamma</strong> : float, default=None</p>
<blockquote>
<div><p>Gamma parameter for the RBF, laplacian, polynomial, exponential chi2
and sigmoid kernels. Interpretation of the default value is left to
the kernel; see the documentation for sklearn.metrics.pairwise.
Ignored by other kernels.</p>
</div></blockquote>
<p><strong>degree</strong> : float, default=3</p>
<blockquote>
<div><p>Degree of the polynomial kernel. Ignored by other kernels.</p>
</div></blockquote>
<p><strong>coef0</strong> : float, default=1</p>
<blockquote>
<div><p>Zero coefficient for polynomial and sigmoid kernels.
Ignored by other kernels.</p>
</div></blockquote>
<p><strong>kernel_params</strong> : mapping of string to any, optional</p>
<blockquote>
<div><p>Additional parameters (keyword arguments) for kernel function passed
as callable object.</p>
</div></blockquote>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Attributes:</th><td class="field-body"><p class="first"><strong>dual_coef_</strong> : array, shape = [n_samples] or [n_samples, n_targets]</p>
<blockquote>
<div><p>Representation of weight vector(s) in kernel space</p>
</div></blockquote>
<p><strong>X_fit_</strong> : {array-like, sparse matrix}, shape = [n_samples, n_features]</p>
<blockquote class="last">
<div><p>Training data, which is also required for prediction</p>
</div></blockquote>
</td>
</tr>
</tbody>
</table>

<pre>
# 06 07 10 11 12 13 14
# [---]                | Adding all sub UIs to main UI     1-2 days
#          [----]      | Implementing Backend Code         2-3 days
#               [----] | Testing all interfaces            1-2 days
</pre>

**Comment by tisaconundrum2** [comment]
Just a thought, but what do you think about making another subfolder for these UI pieces, so as to not overpopulate the regression UI file

**Comment by ryanbanderson** [comment]
Good idea, that would definitely streamline the training UI file.

**Comment by tisaconundrum2** [comment]
Bayesian Ridge has these Parameters,
@ryanbanderson could you select the ones that are most important to you?

- [ ] n_iter 
- [ ] tol 
- [ ] alpha_1 
- [ ] Hyper-parameter 
- [ ] alpha_2 
- [ ] Hyper-parameter 
- [ ] lambda_1 
- [ ] Hyper-parameter 
- [ ] lambda_2 
- [ ] Hyper-parameter 
- [ ] compute_score 
- [ ] fit_intercept 
- [ ] normalize 
- [ ] copy_X 
- [ ] verbose

**Comment by tisaconundrum2** [comment]
ARD is similar as well, 

- [ ] n_iter
- [ ] tol
- [ ] alpha_1
- [ ] Hyper-parameter
- [ ] alpha_2
- [ ] Hyper-parameter
- [ ] lambda_1
- [ ] Hyper-parameter
- [ ] lambda_2
- [ ] Hyper-parameter
- [ ] compute_score
- [ ] threshold_lambda
- [ ] fit_intercept
- [ ] normalize
- [ ] copy_X
- [ ] verbose

**Comment by tisaconundrum2** [comment]
Least Angle Regression (LARS)

- [ ] n_nonzero_coefs
- [ ] fit_intercept
- [ ] positive
- [ ] verbose
- [ ] normalize
- [ ] precompute
- [ ] copy_X
- [ ] eps
- [ ] fit_path

<td class="field-body"><p class="first"><strong>n_nonzero_coefs</strong> : int, optional</p>
<blockquote>
<div><p>Target number of non-zero coefficients. Use <code class="docutils literal"><span class="pre">np.inf</span></code> for no limit.</p>
</div></blockquote>
<p><strong>fit_intercept</strong> : boolean</p>
<blockquote>
<div><p>Whether to calculate the intercept for this model. If set
to false, no intercept will be used in calculations
(e.g. data is expected to be already centered).</p>
</div></blockquote>
<p><strong>positive</strong> : boolean (default=False)</p>
<blockquote>
<div><p>Restrict coefficients to be &gt;= 0. Be aware that you might want to
remove fit_intercept which is set True by default.</p>
</div></blockquote>
<p><strong>verbose</strong> : boolean or integer, optional</p>
<blockquote>
<div><p>Sets the verbosity amount</p>
</div></blockquote>
<p><strong>normalize</strong> : boolean, optional, default False</p>
<blockquote>
<div><p>If True, the regressors X will be normalized before regression.
This parameter is ignored when <cite>fit_intercept</cite> is set to False.
When the regressors are normalized, note that this makes the
hyperparameters learnt more robust and almost independent of the number
of samples. The same property is not valid for standardized data.
However, if you wish to standardize, please use
<cite>preprocessing.StandardScaler</cite> before calling <cite>fit</cite> on an estimator
with <cite>normalize=False</cite>.</p>
</div></blockquote>
<p><strong>precompute</strong> : True | False | ‘auto’ | array-like</p>
<blockquote>
<div><p>Whether to use a precomputed Gram matrix to speed up
calculations. If set to <code class="docutils literal"><span class="pre">'auto'</span></code> let us decide. The Gram
matrix can also be passed as argument.</p>
</div></blockquote>
<p><strong>copy_X</strong> : boolean, optional, default True</p>
<blockquote>
<div><p>If <code class="docutils literal"><span class="pre">True</span></code>, X will be copied; else, it may be overwritten.</p>
</div></blockquote>
<p><strong>eps</strong> : float, optional</p>
<blockquote>
<div><p>The machine-precision regularization in the computation of the
Cholesky diagonal factors. Increase this for very ill-conditioned
systems. Unlike the <code class="docutils literal"><span class="pre">tol</span></code> parameter in some iterative
optimization-based algorithms, this parameter does not control
the tolerance of the optimization.</p>
</div></blockquote>
<p><strong>fit_path</strong> : boolean</p>
<blockquote>
<div><p>If True the full path is stored in the <code class="docutils literal"><span class="pre">coef_path_</span></code> attribute.
If you compute the solution for a large problem or many targets,
setting <code class="docutils literal"><span class="pre">fit_path</span></code> to <code class="docutils literal"><span class="pre">False</span></code> will lead to a speedup, especially
with a small alpha.</p>
</div></blockquote>
</td>

**Comment by ryanbanderson** [comment]
Let's err on the side of including most parameters for regression train methods. We could even include the ones that we don't think users will ever want to modify, just to be explicit about what the defaults are. As long as we set the defaults properly it doesn't hurt to add them. Eventually, we might want to have hidden "expert parameters" for some methods that can optionally be revealed and edited. For now, the main thing is to get the functionality in place.

**Comment by tisaconundrum2** [comment]
Sounds good :)

**Comment by tisaconundrum2** [comment]
All UIs have been created, Now working on backend. I'll be moving these to a subfolder as well.
![image](https://user-images.githubusercontent.com/11879769/27980582-fecc7ad4-6334-11e7-978d-cbcfcf4990dd.png)

**Comment by tisaconundrum2** [comment]
Now finished with implementing backend to display UI's
Continuing work on getting proper information from the UI's
![image](https://user-images.githubusercontent.com/11879769/28136671-6146b9a4-66ff-11e7-9962-6e2968db1d90.png)

![image](https://user-images.githubusercontent.com/11879769/28136619-302e80cc-66ff-11e7-9c7d-909058251ddd.png)

**Comment by tisaconundrum2** [comment]
regression.py is now choking at line 180 in the fit() function.
this has something to do with how large our data is, because we're getting an Infinity error.

Perhaps  we need to run full workflows, lets do this and see if we get a different result

**Comment by tisaconundrum2** [comment]
@ryanbanderson should CV be on by default?
