### ISSUE TITLE
Regression Method Bugs

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#72]
LassoLARS bugs:
Error: __init__() got an unexpected keyword argument 'model'

**Comment by tisaconundrum2** [comment]
GP bugs:
Found array with 0 feature(s) (shape=(2074, 0)) while a minimum of 1 is required.

**Comment by ryanbanderson** [comment]
LARS:
Error: __init__() got an unexpected keyword argument 'n_nonzero_coefs'

**Comment by tisaconundrum2** [comment]
Really weird, these init() things don't show up when I'm debugging carefully line by line.

**Comment by tisaconundrum2** [comment]
https://stackoverflow.com/questions/38817976/init-got-an-unexpected-keyword-argument
The problem here is that the LARS initializer does not take parameters called `n_nonzero_coefs`
I'll dig around in the sklearn package and see if something is amiss with the way i wrote the functions.

**Comment by tisaconundrum2** [comment]
Pull request #75 fixes this

**Comment by ryanbanderson** [comment]
Does this fix the GP bug too?

**Comment by tisaconundrum2** [comment]
Just the CV init() problems

**Comment by tisaconundrum2** [comment]
I"ll dig into the GP problem

**Comment by tisaconundrum2** [comment]
Ridge and RidgeCV will need to be seperated. Their parameters are vastly different

![image](https://user-images.githubusercontent.com/11879769/28693840-9fe4db22-72db-11e7-8fba-555b50cedfe4.png)

![image](https://user-images.githubusercontent.com/11879769/28693848-aae8dcda-72db-11e7-9397-42c055c78d28.png)

**Comment by tisaconundrum2** [comment]
No errors were found in the regression algorithms...
I'll finish up adding Ridge CV

**Comment by ryanbanderson** [comment]
Ridge and Elastic Net don't run. For elastic_net I get: 
__init__() got an unexpected keyword argument 'warm_start'

For Ridge (with CV checked) I get:
'regression_train_' object has no attribute 'elastic_net'

Because these occur in try/except, I can't tell where exactly the problem is.

**Comment by ryanbanderson** [comment]
LARS with CV selected gives: 
__init__() got an unexpected keyword argument 'n_nonzero_coefs'

**Comment by ryanbanderson** [comment]
Lasso LARS doesn't run, just immediately grays out without doing anything. I thought these had been debugged...

**Comment by tisaconundrum2** [comment]
I think I can now close this issue because the future implementation utilizes direct sklearn library access. A good portion of these errors stem from the fact that `__init__()` never actually has the variable functions that I was asking for. 

In other words these `Error: init() got an unexpected keyword` come from not actually checking the internals in each of the packages of sklearn. 

Please feel free to take a look at 5668bab12356982b87cdc5bc89759415916ae36a to see what I mean
You'll notice that I'm importing each sklearn package directly into the module.
