### ISSUE TITLE
Problem with model ranges in CV

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#81]
Reported by Sam Clegg: "The CV function does not work. The results for the full model are the same for the shorter range models."

**Comment by ryanbanderson** [comment]
Confirmed: yrange isn't used anywhere!

**Comment by tisaconundrum2** [comment]
Issue with min and max. Fix these

**Comment by ryanbanderson** [comment]
These lines from do_regression_train in backEndProcessing are relevant:

`               x = self.data[datakey].df[xvars]
                y = self.data[datakey].df[yvars]
                x = np.array(x)
                y = np.array(y)
                ymask = np.squeeze((y > yrange[0]) & (y < yrange[1]))
                y = y[ymask]
                x = x[ymask, :]
                self.models[modelkey].fit(x, y)`

**Comment by tisaconundrum2** [comment]
This should be fixed in PR https://github.com/ryanbanderson/PySAT_Point_Spectra_GUI/pull/7

**Comment by ryanbanderson** [comment]
- Had to delete the "~" from the fix to make it remove rows outside the yrange rather than inside.
- Had to connect the spinboxes in the UI so that when changed, yrange gets updated.
- Had to change it so that the rows are removed from a copy of the data rather than altering the original data frame.
