### ISSUE TITLE
Save workflows to the output path

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#91]
Currently they save to the point_spectra_gui directory.

**Comment by tisaconundrum2** [comment]
Fixed this in https://github.com/ryanbanderson/PySAT_Point_Spectra_GUI/pull/11

**Comment by tisaconundrum2** [comment]
Fixed in https://github.com/ryanbanderson/PySAT_Point_Spectra_GUI/pull/11

**Comment by ryanbanderson** [comment]
Won't this just save the workflows to the desktop rather than the path chosen in the file_outpath module?

**Comment by tisaconundrum2** [comment]
Ok this has been fixed

**Comment by tisaconundrum2** [comment]
![4e084f1c-87c5-4f98-8ed3-d077dbb96592](https://user-images.githubusercontent.com/11879769/30189122-fb81c996-93e6-11e7-8d6c-ecc2f6ed3a04.gif)
