### ISSUE TITLE
'spectral_data' object is not subscriptable

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#93]
During the `do_plot` call, this error shows up.
the `example_train_predict.wrf` was used

**Comment by ryanbanderson** [comment]
What line does the error occur on?

**Comment by tisaconundrum2** [comment]
Error occurs in backEndProcessing.py: 496

        except:
            x = self.data[datakey][xvar]
            y = self.data[datakey][yvar]

**Comment by ryanbanderson** [comment]
Problem appears to be that when the workflow is restored, the # of components for PLS is set to zero instead of the correct number. So this is a problem with restoring the Regression - Train module.

**Comment by tisaconundrum2** [comment]
I had noticed this as well, I was thinking this was the culprit

**Comment by tisaconundrum2** [comment]
Issue will be resolved in future implementation
