### ISSUE TITLE
Better naming of CV results

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#96]
Currently they are just named "CV Results" and if you run two types of CV in one workflow, the first one gets overwritten.

**Comment by tisaconundrum2** [comment]
```
\backEndProcessing.py
\ui_modules\regression_train_.py
\ui_modules\remove_baseline_.py
```
Based on my search algorithm, these 3 files have `CV Results` in them

**Comment by tisaconundrum2** [comment]
Use the model key to differentiate the CV results
