### ISSUE TITLE
Program crashes when modifying norm settings

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#97]
If you delete a normalization range and then try to edit the remaining ranges, the program crashes. Need to make sure this is resolved with the "future" implementation of normalization.

**Comment by tisaconundrum2** [comment]
Yeah, this shouldn't be an issue with the future implementation, as it doesn't use dynamic adding any more.

**Comment by tisaconundrum2** [comment]
Issue is resolved in future implementation
